// GENERATED from lib/db schema via drizzle-kit export (idempotent). Regenerate when the schema changes.
export const BOOTSTRAP_STATEMENTS: string[] = [
 "CREATE TABLE IF NOT EXISTS \"accounts\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"broker\" text NOT NULL,\n\t\"balance\" numeric(18, 2) DEFAULT '0' NOT NULL,\n\t\"equity\" numeric(18, 2) DEFAULT '0' NOT NULL,\n\t\"margin\" numeric(18, 2) DEFAULT '0' NOT NULL,\n\t\"margin_level\" numeric(10, 2),\n\t\"currency\" text DEFAULT 'USD' NOT NULL,\n\t\"account_type\" text DEFAULT 'demo' NOT NULL,\n\t\"status\" text DEFAULT 'active' NOT NULL,\n\t\"notes\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL\n)",
 "CREATE TABLE IF NOT EXISTS \"trades\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"account_id\" integer NOT NULL,\n\t\"signal_id\" integer,\n\t\"symbol\" text NOT NULL,\n\t\"direction\" text NOT NULL,\n\t\"open_price\" numeric(18, 5) NOT NULL,\n\t\"close_price\" numeric(18, 5),\n\t\"stop_loss\" numeric(18, 5),\n\t\"take_profit\" numeric(18, 5),\n\t\"lot_size\" numeric(10, 2) NOT NULL,\n\t\"opened_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"closed_at\" timestamp with time zone,\n\t\"status\" text DEFAULT 'open' NOT NULL,\n\t\"pnl\" numeric(18, 2),\n\t\"pips\" numeric(10, 1),\n\t\"risk_reward\" numeric(10, 2),\n\t\"strategy\" text NOT NULL,\n\t\"reason_chain\" text NOT NULL,\n\t\"annotations\" text,\n\t\"holding_time\" integer,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL\n)",
 "CREATE TABLE IF NOT EXISTS \"signals\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"symbol\" text NOT NULL,\n\t\"direction\" text NOT NULL,\n\t\"confidence\" numeric(5, 4) NOT NULL,\n\t\"strategy\" text NOT NULL,\n\t\"concepts\" text,\n\t\"entry_zone\" text NOT NULL,\n\t\"target_zone\" text,\n\t\"stop_zone\" text,\n\t\"entry_low\" numeric(18, 8),\n\t\"entry_high\" numeric(18, 8),\n\t\"stop_level\" numeric(18, 8),\n\t\"target1_level\" numeric(18, 8),\n\t\"target2_level\" numeric(18, 8),\n\t\"levels\" text,\n\t\"reasoning\" text,\n\t\"status\" text DEFAULT 'active' NOT NULL,\n\t\"execution_status\" text DEFAULT 'generated' NOT NULL,\n\t\"execution_reason\" text,\n\t\"contract_id\" bigint,\n\t\"dispatched_at\" timestamp with time zone,\n\t\"expires_at\" timestamp with time zone,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL\n)",
 "CREATE TABLE IF NOT EXISTS \"strategies\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"type\" text NOT NULL,\n\t\"description\" text NOT NULL,\n\t\"explanation\" text,\n\t\"weight\" numeric(4, 3),\n\t\"active\" boolean DEFAULT true NOT NULL,\n\t\"parameters\" text,\n\t\"trade_count\" integer DEFAULT 0 NOT NULL,\n\t\"win_rate\" numeric(5, 4),\n\t\"concepts\" text,\n\t\"rules\" text,\n\t\"sources_used\" integer DEFAULT 0 NOT NULL,\n\t\"words_analyzed\" integer DEFAULT 0 NOT NULL,\n\t\"summary\" text,\n\t\"synthesized_at\" timestamp with time zone,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL\n)",
 "CREATE TABLE IF NOT EXISTS \"reports\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"type\" text NOT NULL,\n\t\"period\" text NOT NULL,\n\t\"win_rate\" numeric(5, 4) DEFAULT '0' NOT NULL,\n\t\"total_pnl\" numeric(18, 2) DEFAULT '0' NOT NULL,\n\t\"max_drawdown\" numeric(10, 4) DEFAULT '0' NOT NULL,\n\t\"trades_count\" integer DEFAULT 0 NOT NULL,\n\t\"long_count\" integer DEFAULT 0 NOT NULL,\n\t\"short_count\" integer DEFAULT 0 NOT NULL,\n\t\"avg_holding_time\" numeric(10, 2),\n\t\"risk_reward\" numeric(10, 2),\n\t\"strategy_adherence\" numeric(5, 4) DEFAULT '0' NOT NULL,\n\t\"gambling_score\" numeric(5, 4) DEFAULT '1' NOT NULL,\n\t\"uptime_percent\" numeric(5, 2),\n\t\"scores\" text,\n\t\"total_score\" numeric(5, 2),\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n)",
 "CREATE TABLE IF NOT EXISTS \"brain_layers\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"layer_type\" text NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"description\" text NOT NULL,\n\t\"status\" text DEFAULT 'idle' NOT NULL,\n\t\"metrics\" text,\n\t\"output_signal\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL\n)",
 "CREATE TABLE IF NOT EXISTS \"education_sources\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"kind\" text NOT NULL,\n\t\"title\" text NOT NULL,\n\t\"author\" text,\n\t\"source_url\" text,\n\t\"content_text\" text,\n\t\"status\" text DEFAULT 'pending' NOT NULL,\n\t\"chunks_count\" integer DEFAULT 0 NOT NULL,\n\t\"vector_count\" integer DEFAULT 0 NOT NULL,\n\t\"transcript_preview\" text,\n\t\"metadata\" text,\n\t\"error_message\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL\n)",
 "CREATE TABLE IF NOT EXISTS \"broker_connections\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"broker\" text NOT NULL,\n\t\"label\" text NOT NULL,\n\t\"environment\" text DEFAULT 'real' NOT NULL,\n\t\"account_id\" integer,\n\t\"credential\" text NOT NULL,\n\t\"status\" text DEFAULT 'disconnected' NOT NULL,\n\t\"last_sync_at\" timestamp with time zone,\n\t\"last_error\" text,\n\t\"enabled\" boolean DEFAULT true NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL\n)",
 "CREATE TABLE IF NOT EXISTS \"bot_config\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"enabled\" boolean DEFAULT false NOT NULL,\n\t\"autotrade_mode\" text DEFAULT 'off' NOT NULL,\n\t\"risk_per_trade_pct\" numeric(5, 2) DEFAULT '1.00' NOT NULL,\n\t\"max_concurrent_positions\" integer DEFAULT 3 NOT NULL,\n\t\"max_daily_loss_pct\" numeric(5, 2) DEFAULT '5.00' NOT NULL,\n\t\"min_confidence\" numeric(4, 3) DEFAULT '0.780' NOT NULL,\n\t\"allowed_instruments\" text DEFAULT '' NOT NULL,\n\t\"killzones\" text DEFAULT '' NOT NULL,\n\t\"small_account_max_risk_pct\" numeric(5, 2) DEFAULT '10.00' NOT NULL,\n\t\"min_risk_reward\" numeric(5, 2) DEFAULT '2.00' NOT NULL,\n\t\"atr_percentile_min\" numeric(5, 2) DEFAULT '15.00' NOT NULL,\n\t\"atr_percentile_max\" numeric(5, 2) DEFAULT '90.00' NOT NULL,\n\t\"efficiency_ratio_min\" numeric(5, 3) DEFAULT '0.150' NOT NULL,\n\t\"min_stop_atr\" numeric(5, 2) DEFAULT '1.00' NOT NULL,\n\t\"max_per_asset_class\" integer DEFAULT 2 NOT NULL,\n\t\"notes\" text,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL\n)",
 "CREATE TABLE IF NOT EXISTS \"knowledge_chunks\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"source_id\" integer NOT NULL,\n\t\"chunk_index\" integer NOT NULL,\n\t\"content\" text NOT NULL,\n\t\"word_count\" integer DEFAULT 0 NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n)",
 "CREATE TABLE IF NOT EXISTS \"candles\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"symbol\" text NOT NULL,\n\t\"timeframe\" text NOT NULL,\n\t\"open_time\" timestamp with time zone NOT NULL,\n\t\"open\" numeric(18, 8) NOT NULL,\n\t\"high\" numeric(18, 8) NOT NULL,\n\t\"low\" numeric(18, 8) NOT NULL,\n\t\"close\" numeric(18, 8) NOT NULL,\n\t\"volume\" numeric(18, 4),\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n)",
 "CREATE TABLE IF NOT EXISTS \"trade_reviews\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"trade_id\" integer NOT NULL,\n\t\"account_id\" integer NOT NULL,\n\t\"symbol\" text NOT NULL,\n\t\"direction\" text NOT NULL,\n\t\"strategy\" text NOT NULL,\n\t\"reasoning\" text NOT NULL,\n\t\"claimed_concepts\" text DEFAULT '[]' NOT NULL,\n\t\"entry_price\" numeric(18, 8) NOT NULL,\n\t\"stop_price\" numeric(18, 8),\n\t\"target_price\" numeric(18, 8),\n\t\"close_price\" numeric(18, 8),\n\t\"outcome\" text NOT NULL,\n\t\"pnl\" numeric(18, 2),\n\t\"classification\" text NOT NULL,\n\t\"evidence_status\" text NOT NULL,\n\t\"evidence_summary\" text NOT NULL,\n\t\"candles_examined\" integer DEFAULT 0 NOT NULL,\n\t\"closed_at\" timestamp with time zone,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n)",
 "CREATE TABLE IF NOT EXISTS \"trade_performance\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"dimension\" text NOT NULL,\n\t\"key\" text NOT NULL,\n\t\"trade_count\" integer DEFAULT 0 NOT NULL,\n\t\"win_count\" integer DEFAULT 0 NOT NULL,\n\t\"loss_count\" integer DEFAULT 0 NOT NULL,\n\t\"total_pnl\" numeric(18, 2) DEFAULT '0' NOT NULL,\n\t\"weighted_trades\" numeric(18, 8) DEFAULT '0' NOT NULL,\n\t\"weighted_wins\" numeric(18, 8) DEFAULT '0' NOT NULL,\n\t\"last_outcome_at\" timestamp with time zone,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL\n)",
 "CREATE TABLE IF NOT EXISTS \"app_owner\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"password_hash\" text NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n)",
 "CREATE TABLE IF NOT EXISTS \"app_secrets\" (\n\t\"key\" text PRIMARY KEY NOT NULL,\n\t\"value\" text NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL\n)",
 "CREATE TABLE IF NOT EXISTS \"deriv_frames\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"received_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"direction\" text NOT NULL,\n\t\"kind\" text NOT NULL,\n\t\"signal_id\" integer,\n\t\"contract_id\" text,\n\t\"payload\" text NOT NULL,\n\t\"ok\" boolean\n)",
 "CREATE UNIQUE INDEX IF NOT EXISTS \"candles_symbol_tf_time\" ON \"candles\" USING btree (\"symbol\",\"timeframe\",\"open_time\")",
 "CREATE UNIQUE INDEX IF NOT EXISTS \"trade_reviews_trade_id_unique\" ON \"trade_reviews\" USING btree (\"trade_id\")",
 "CREATE INDEX IF NOT EXISTS \"trade_reviews_closed_at_idx\" ON \"trade_reviews\" USING btree (\"closed_at\")",
 "CREATE UNIQUE INDEX IF NOT EXISTS \"trade_performance_dimension_key_unique\" ON \"trade_performance\" USING btree (\"dimension\",\"key\")"
];
